### ISSUE TITLE
只有完整路径能查到东西

### ISSUE THREAD

**Issue by amacelite** [Seraphli/obsidian-aggregator#1]
我用的时候发现设置scope的时候，只有完整路径能查到东西，我看应该是关于路径匹配的代码没有返回值导致的：“const scopeMatches = partRegex.filter((regex) => {  ”这个方法没有返回值，加上应该就好了。
另外，表示下感谢，这个插件很有用，标签之类的内容越来越多后，分散在各处，很需要这样的工具来做汇聚。

**Comment by Seraphli** [comment]
修复啦, 之前测试的时候没发现引入了这个bug. 感谢提醒.
