### ISSUE TITLE
Default sorting

### ISSUE THREAD

**Issue by braimen** [Seraphli/obsidian-aggregator#2]
The plugin is very helpful and I use it a lot, thanks for that!
Unfortunately, the generated list does not seems to be sorted correctly. It would be great if I could influence this (ASC/DESC), or if there is a reliable default sort order.

**Comment by Seraphli** [comment]
That's a good idea. Can you provide more details about how you want to sort all files? I will try to implement this feature in a more general way.

**Comment by braimen** [comment]
Thanks for the fast reply!
It would be a dream to be able to specify not only the direction (ASC/DESC), but also what to sort by. <filename> could be the default, sorting by the found string (<match>) would certainly be very helpful as well. Being able to sort by created time (<ctime>) or modified time (<mtime>) would just be icing on the cake, but not important.
Maybe you could define another block like:
```yaml
sorting:
    - by: filename | match | ctime | mtime
      direction: ASC | DESC
```
<direction> is not a good term, maybe you find a better one.

**Comment by Seraphli** [comment]
Thanks. I got it. I will implement such a feature later.

**Comment by braimen** [comment]
Cool. Thanks!
I would like a add `<fullpath>` to `sorting.by`: so that you can sort by file name alone and by the full path with file name (if that is not too much to expect). This could be handy in some scenarios.

**Comment by Seraphli** [comment]
Check out the new version. I have updated the usage and explanation in the README. Let me know if you have more questions.

**Comment by braimen** [comment]
Thanks a lot for the update! It is really powerful and does much more than I had hoped.
I just had to figure out that the one fileIndicator parameter `file` was changed to `result`. Everything else worked instantly.

**Comment by Seraphli** [comment]
Yes, I have changed the `file` to `result`, so now the fileIndicator support all fields, and the template can be more complex.
