### ISSUE TITLE
when use two tags together,the aggregator  match none of them 

### ISSUE THREAD

**Issue by mdshwt** [Seraphli/obsidian-aggregator#3]
Hi,you have  developed a really cool plugin.
But I have a question,if I use two tags in the annotation once a time, such as #idea  # highlight,I can't find them in idea field nor highlight field.More,if i have 3 or more tags for a certain annotation ,how should I write the code in the code block ,I think I should change the  regex  in the aggregator field ,but I want to know if you have a better sollution ,it's really annoyed to write diffierent regex for different amount tags .
![image](https://user-images.githubusercontent.com/67129523/230903443-0bc04f19-8287-4006-a8d1-d2911665a155.png)

Thank you for your help
Best wishes.

**Comment by Seraphli** [comment]
Change the RegEx to this. Sorry for the late reply.
```
>%%\n>```annotation-json\n>.*\n>```\n>%%\n>\*%%PREFIX%%.*\n>%%LINK%%.*\n>%%COMMENT%%\n([^%]*\n)*>%%TAGS%%\n>.*\#idea.*\n\^[a-zA-Z0-9]*
```

**Comment by mdshwt** [comment]
thank you for your generous help

**Comment by Seraphli** [comment]
No problem. I will close this for now. Feel free to leave a comment if you have a new question.
