### ISSUE TITLE
Summarize the content of a certain title

### ISSUE THREAD

**Issue by alanodididi** [Seraphli/obsidian-aggregator#4]
Hello, I would like to ask if this plugin can help count the content under specific headings in files under specific folders. I have tried multiple times to write code using GPT but failed. Can you provide a similar example? Thank you very much. The dataview plugin seems to be doing well. I would like to ask if this plugin can help count the content under specific headings in specific folders and provide a similar example. Thank you very much, The dataview plugin seems to be unable to perform this function

**Comment by Seraphli** [comment]
Yes, you can. That's the exact reason why I created this plugin. Here is a code I'm been using, and what it looks like.

```aggregator
scope:
    - ReadingNotes/
matches:
    - regex: '[\S\s]+'
      template: >-
        {{eval "return data.result.content.contains('#summary')? '✓': 'x'"}}
order:
    fields: mtime
    orders: desc
fileIndecator: >-
    |{{result.index}}|[[{{result.basename}}]]|{{eval "return moment.unix(data.result.mtime/1000).format('YYYY-MM-DD')"}}|{{template}}|
joinString: "\n"
decorator: |-
    Notes: {{eval "return (data.templates.match(/✓/g)).length"}}/{{eval "return data.summaries.length"}}
    
    | ID  | Note | ModifyTime | Done        |
    | --- | ---- | ---------- | ----------- |
    {{templates}}
```

![image](https://github.com/Seraphli/obsidian-aggregator/assets/1586755/c4d7a397-4de9-401c-9203-95eb896a3414)

**Comment by alanodididi** [comment]
> Yes, you can. That's the exact reason why I created this plugin. Here is a code I'm been using, and what it looks like.是的， 你可以的。这就是我创建这个插件的确切原因。这是我一直在使用的代码，以及它的外观。
> 
> ```
> scope:
>     - ReadingNotes/
> matches:
>     - regex: '[\S\s]+'
>       template: >-
>         {{eval "return data.result.content.contains('#summary')? '✓': 'x'"}}
> order:
>     fields: mtime
>     orders: desc
> fileIndecator: >-
>     |{{result.index}}|[[{{result.basename}}]]|{{eval "return moment.unix(data.result.mtime/1000).format('YYYY-MM-DD')"}}|{{template}}|
> joinString: "\n"
> decorator: |-
>     Notes: {{eval "return (data.templates.match(/✓/g)).length"}}/{{eval "return data.summaries.length"}}
>     
>     | ID  | Note | ModifyTime | Done        |
>     | --- | ---- | ---------- | ----------- |
>     {{templates}}
> ```
> 
> ![image](https://user-images.githubusercontent.com/1586755/282525552-c4d7a397-4de9-401c-9203-95eb896a3414.png)

Amazing, I succeeded, just a simple learning of the regex， I can match anything I want, thank you for your help!
