### ISSUE TITLE
footnotes

### ISSUE THREAD

**Issue by alanodididi** [Seraphli/obsidian-aggregator#5]
This plugin doesn't seem to be able to count content in footnotes, have you tried it? thank you。

**Comment by Seraphli** [comment]
Please provide an example and the code you used.

**Comment by alanodididi** [comment]
![image](https://github.com/Seraphli/obsidian-aggregator/assets/64760894/3e1f0bd2-6ad5-4efb-824f-2b6e82c8d860)
![image](https://github.com/Seraphli/obsidian-aggregator/assets/64760894/c9b2dad7-eca8-43fa-ae08-4291dd44e443)

**Comment by Seraphli** [comment]
没理解你截图的意思，看上去你截图里面已经得到了footnote信息。还有你似乎是在搜索本文件里面的内容，如果是这样的话，应该使用
```
scope:
    - Current File
```
另外请贴上原本的md文件，方便我测试。

**Comment by alanodididi** [comment]
![image](https://github.com/Seraphli/obsidian-aggregator/assets/64760894/6432e958-7575-44ce-9ba0-2d98f6648e1f)
![image](https://github.com/Seraphli/obsidian-aggregator/assets/64760894/5e300f7b-17cb-467d-ad4a-2f69b3db8a23)
[未命名 30.md](https://github.com/Seraphli/obsidian-aggregator/files/13365376/30.md)

**Comment by Seraphli** [comment]
因为Obsidian的API会直接将footnote渲染成空的，所以你可以考虑替换掉`^`，这样就可以显示出来了

```aggregator
scope:
    - Current File
matches:
    - regex: '\[\^\d+\]:\s.*$'
      template: >-
        {{eval "return data.result.match[0].replace('^','')"}}
```

**Comment by Seraphli** [comment]
另外一个情况是这样的
```aggregator
scope:
    - Current File
matches:
    - regex: '^\[\d+\]\s+.*$'
      template: '{{{result.match.[0]}}}'
```
![image](https://github.com/Seraphli/obsidian-aggregator/assets/1586755/3a163d2c-6b48-499e-9315-dc8c236176c0)

**Comment by alanodididi** [comment]
^被替换掉就不是脚注啦，失去了灵魂


王赢宣
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Seraphli/obsidian-aggregator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月15日(星期三) 晚上11:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Seraphli/obsidian-aggregator] footnotes (Issue #5)





 
因为Obsidian的API会直接将footnote渲染成空的，所以你可以考虑替换掉^，这样就可以显示出来了
 scope:     - Current File matches:     - regex: '\[\^\d+\]:\s.*$'       template: &gt;-         {{eval "return data.result.match[0].replace('^','')"}}

**Comment by Seraphli** [comment]
这个插件只是显示出来结果, 本身脚注在插件渲染的结果里面也不会有作用, 也跳转不到原来的地方的.
